timeout: 1800s
steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build -t us.gcr.io/$PROJECT_ID/web:latest \
        --cache-from us.gcr.io/$PROJECT_ID/web:latest \
        --build-arg CWF_VERSION=$(awk -F\" '/"version":/ {print $4}' package.json) \
        . \
        || exit 1
images: ['us.gcr.io/$PROJECT_ID/web:latest']
