name: Deploy App Engine

on:
  workflow_dispatch:
    inputs:
      version:
        description: Semver version (patch|minor|major)
        required: true
        default: patch
env:
  NODE_VERSION: 14.0.0
  GIT_USER: dtothefp
  GIT_EMAIL: dtothefp@gmail.com
  PROJECT_ID: goodrx-content-prod
  JOB_URL: 'https://github.com/{{ env.GITHUB_REPOSITORY }}/actions/runs/{{ github.job }}'
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy App Engine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: nelonoel/branch-name@v1.0.1
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - run: git fetch --depth=1 origin
      - name: Setup Git
        run: |
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          git remote set-url origin git@github.com:$GITHUB_REPOSITORY.git
          git reset --hard $BRANCH_NAME
          git remote show origin
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Version
        run: |
          sudo yarn global add semver
          CURR_VERSION=$(node -pe "require('./package.json').version");
          VERSION=$(semver -i $LEVEL $CURR_VERSION);
          VERSION=$VERSION node deploy/updateChangelog.js
          git add CHANGELOG.md
          yarn version --${LEVEL}
          echo "VERSION $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        env:
          LEVEL: ${{ github.event.inputs.version }}
      - name: Deploy Message
        run: |
          curl -X POST \
          --data-urlencode \
          "payload={
            \"channel\":\"#fep-alerts\",
            \"username\":\"cwf_release\",
            \"text\":\"[$BRANCH_NAME] <$JOB_URL|CWF Deploy v$VERSION> started :crossed_fingers:\",
            \"icon_emoji\":\":hipster:
          \"}" \
          $SLACK_WEB_HOOK_URL
      - name: GCP Creds
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: 'goodrx-content-prod'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: GCP Cloudbuild
        run: |
          gcloud config set app/cloud_build_timeout 1800;
          gcloud builds submit --config cloudbuild_deploy.yaml . || exit 1;
      - name: GCP App Engine Deploy
        run: |
          gcloud app deploy --no-promote --version=v${VERSION//\./-}-deploy-test --image-url='us.gcr.io/goodrx-content-prod/web:deploy-test' --quiet;
      - name: Push Tags
        run: |
          git push --tags && git push origin $BRANCH_NAME
      - name: Deploy Complete
        if: ${{ success() }}
        run: |
      - name: Deploy Message
        run: |
          curl -X POST \
          --data-urlencode \
          "payload={
            \"channel\":\"#fep-alerts\",
            \"username\":\"cwf_release\",
            \"text\":\"[$BRANCH_NAME] <$JOB_URL|CWF Deploy v$VERSION> finished :tada:\",
            \"icon_emoji\":\":hipster:
          \"}" \
          $SLACK_WEB_HOOK_URL
      - name: Deploy Failed
        if: ${{ failure() }}
        run: |
          curl -X POST \
          --data-urlencode \
          "payload={
            \"channel\":\"#fep-alerts\",
            \"username\":\"cwf_release\",
            \"text\":\"[$BRANCH_NAME] <$JOB_URL|CWF Deploy v$VERSION> failed :face_palm:\",
            \"icon_emoji\":\":hipster:
          \"}" \
          $SLACK_WEB_HOOK_URL
