name: Deploy App Engine

on:
  workflow_dispatch:
    inputs:
      version:
        description: Semver version (patch|minor|major)
        required: true
        default: patch
env:
  NODE_VERSION: 14.0.0
  GIT_USER: dtothefp
  GIT_EMAIL: dtothefp@gmail.com
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy App Engine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Test Write Env
        run: echo "TEST=TEST" >> $GITHUB_ENV
      - name: Test READ Env
        run: echo "TEST: $TEST"
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: GCP Creds
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '285.0.0'
          project_id: 'goodrx-content-prod'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Setup Git
        run: |
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          echo "GIT_URL=git@github.com:${GITHUB_REPOSITORY}.git" >> $GITHUB_ENV
        env:
          GITHUB_REPOSITORY: ${{ env.GITHUB_REPOSITORY }}
      - name: Git Credentials
        run: |
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          git remote set-url origin $GIT_URL
          git remote show origin
      - name: Version
        run: |
          yarn version --${VERSION}
          PKG_VERSION=$(node -pe "require('./package.json').version");
          echo "PKG_VERSION=${PKG_VERSION}" >> $GITHUB_ENV
        env:
          VERSION: ${{ github.event.inputs.version }}
      - name: Check the version
        run: echo ${{ env.PKG_VERSION }}
      - name: GCP App Engine Describe
        run: gcloud app describe
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
