name: Deploy App Engine

on:
  workflow_dispatch:
    inputs:
      version:
        description: Semver version (patch|minor|major)
        required: true
        default: patch
env:
  NODE_VERSION: 14.0.0
  GIT_USER: dtothefp
  GIT_EMAIL: dtothefp@gmail.com
  PROJECT_ID: goodrx-content-prod
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy App Engine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - uses: webfactory/ssh-agent@v0.2.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Setup Git
        run: |
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL
          git remote set-url origin git@github.com:$GITHUB_REPOSITORY.git
          git remote show origin
      - uses: actions/setup-node@master
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Version
        run: |
          yarn version --${VERSION}
          echo "VERSION=$(node -pe "require('./package.json').version")" >> $GITHUB_ENV
        env:
          VERSION: ${{ github.event.inputs.version }}
      - run: echo "VERSION $VERSION"
      - name: GCP Creds
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '285.0.0'
          project_id: 'goodrx-content-prod'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: GCP Cloudbuild
        run: |
          gcloud config set project $PROJECT_ID;
          gcloud config set app/cloud_build_timeout 1800;
          gcloud builds submit --config cloudbuild_deploy.yaml . || exit 1;
      - name: GCP App Engine Deploy
        run: |
          gcloud app deploy --no-promote --version=${VERSION//\./-} --image-url='us.gcr.io/goodrx-content-prod/web:latest' --quiet;
      - name: Push Tags
        run: git push --tags && git push
